name: Create Github Release on Version Change

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 7

      - name: Install dependencies
        run: |
          pnpm i

      - name: Build
        id: build
        run: |
          pnpm build

      - name: Check version
        id: check_version
        run: |
          tag="v$(node -pe "require('./package.json').version")"
          if ! [ $(git tag -l "$tag") ]; then
            echo "changed=1" >> $GITHUB_OUTPUT 
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Package
        id: package
        if: steps.check_version.outputs.changed
        run: |
          pnpm pack
          echo "package=$(find . -name '*.tgz')" >> $GITHUB_OUTPUT
          echo "schema=ducktails.schema.json" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        if: steps.check_version.outputs.changed
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          tag=${{ steps.check_version.outputs.tag }}
          package=${{ steps.package.outputs.package }}
          schema=${{ steps.package.outputs.schema }}
          gh release create "$tag" "$package" "$schema" \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes
